# Generated by Django 4.0.3 on 2022-04-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoprj', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
